### Login User
# @name loginUser
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "admin@autoawake.com",
  "password": "securepassword"
}

### Log Alert
# @name logAlert
POST http://localhost:3000/alerts/
Content-Type: application/json
Authorization: Bearer {{loginUser.response.body.token}}

{
  "trip_id": 1,
  "alert_type": "DROWSINESS",
  "severity": "HIGH",
  "message": "Driver eyes closed for 3 seconds"
}

### Get Alerts by Trip
GET http://localhost:3000/alerts/trip/1
Authorization: Bearer {{loginUser.response.body.token}}

### Control Device (Buzzer ON)
POST http://localhost:3000/alerts/control/encender_buzzer
Content-Type: application/json
Authorization: Bearer {{loginUser.response.body.token}}

### Control Device (Buzzer OFF)
POST http://localhost:3000/alerts/control/apagar_buzzer
Content-Type: application/json
Authorization: Bearer {{loginUser.response.body.token}}

### Control Device (LED ON)
POST http://localhost:3000/alerts/control/encender_led
Content-Type: application/json
Authorization: Bearer {{loginUser.response.body.token}}

### Control Device (LED OFF)
POST http://localhost:3000/alerts/control/apagar_led
Content-Type: application/json
Authorization: Bearer {{loginUser.response.body.token}}
