### Get All Devices
GET http://localhost:3000/devices/

### Update Device Status
PUT http://localhost:3000/devices/1/status
Content-Type: application/json

{
  "status": "ONLINE",
  "firmware_version": "v1.2.3"
}
