### Create Driver
# @name createDriver
POST http://localhost:3000/drivers/
Content-Type: application/json

{
  "first_name": "Carlos",
  "last_name": "Sainz",
  "license_number": "LIC-55555",
  "status": "ACTIVE"
}

### Get All Drivers
GET http://localhost:3000/drivers/

### Get Driver by ID
GET http://localhost:3000/drivers/{{createDriver.response.body.driver_id}}

### Deactivate Driver
DELETE http://localhost:3000/drivers/{{createDriver.response.body.driver_id}}
