### Open Issue
# @name openIssue
POST http://localhost:3000/issues/
Content-Type: application/json

{
  "vehicle_id": 1,
  "issue_type": "MECHANICAL",
  "description": "Check engine light on"
}

### Get All Issues
GET http://localhost:3000/issues/

### Close Issue
POST http://localhost:3000/issues/1/close
