### Start Trip
# @name startTrip
POST http://localhost:3000/trips/
Content-Type: application/json

{
  "vehicle_id": 1,
  "driver_id": 1,
  "origin": "Warehouse A",
  "destination": "Store B"
}

### Get Trip by ID
GET http://localhost:3000/trips/{{startTrip.response.body.trip_id}}

### End Trip
POST http://localhost:3000/trips/{{startTrip.response.body.trip_id}}/end
Content-Type: application/json

{
  "status": "FINISHED"
}

### Get Trips by Driver
GET http://localhost:3000/trips/driver/1

### Get Trips by Vehicle
GET http://localhost:3000/trips/vehicle/1
