### Create Vehicle
# @name createVehicle
POST http://localhost:3000/vehicles/
Content-Type: application/json

{
  "plate": "ABC-123",
  "brand": "Ford",
  "model": "Raptor",
  "status": "ACTIVE"
}

### Get All Vehicles
GET http://localhost:3000/vehicles/

### Get Vehicle by ID
GET http://localhost:3000/vehicles/{{createVehicle.response.body.vehicle_id}}

### Update Vehicle Status
PUT http://localhost:3000/vehicles/{{createVehicle.response.body.vehicle_id}}/status
Content-Type: application/json

{
  "status": "MAINTENANCE"
}
